### ISSUE TITLE
Phone - New indicator type with tools

### ISSUE THREAD

**Issue by rc-austinoneil** [rc-austinoneil/Indicator-Search#20]
**Phone Number:**
- https://numverify.com/
- IP Quality Score phone number API

**Comment by scorpioqueenlove** [comment]
i have an account with numverify i get api is not defined, how do i fix that?

**Comment by scorpioqueenlove** [comment]
> Hi @scorpioqueenlove, I apologize. I had GitHub notifications apparently turned off. There has been many changes within the last couple of weeks. Is this still a problem for you if you `git pull` again??

hello yess this is still a problem. how do i add it.

**Comment by rc-austinoneil** [comment]
Are you just trying to get the numverify to work in general or with Indicator Search? I noticed you posted a similar issue on someone else's project. If you're trying to use numverify with my project, check out the [setup doc](https://github.com/rc-austinoneil/Indicator-Search/blob/master/docs/setup.md) to get started otherwise, I'd check numverify docs for help.

**Comment by scorpioqueenlove** [comment]
> Are you just trying to get the numverify API to work in general or with Indicator Search? I noticed you posted a similar issue on someone else's project. If you're trying to use numverify with my project, check out the [setup doc](https://github.com/rc-austinoneil/Indicator-Search/blob/master/docs/setup.md) to get started otherwise, I'd check numverify docs for help.

i keep getting its not defined

**Comment by rc-austinoneil** [comment]
I would recommend reaching out to numverify if thats the case. I unfortunately can't help you on this one.
